//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersoneManagement.Web.StateProvinceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StateProvinceDTO", Namespace="http://schemas.datacontract.org/2004/07/AdventureWorks.Model")]
    [System.SerializableAttribute()]
    public partial class StateProvinceDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PersoneManagement.Web.StateProvinceService.CountryRegion[] CountriesRegionsDdlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryRegionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryRegionNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnlyStateProvinceFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Web.Mvc.SelectListItem[] SalesTerritorriesDdlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateProvinceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateProvinceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TerritorryNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TerritoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid rowguidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersoneManagement.Web.StateProvinceService.CountryRegion[] CountriesRegionsDdl {
            get {
                return this.CountriesRegionsDdlField;
            }
            set {
                if ((object.ReferenceEquals(this.CountriesRegionsDdlField, value) != true)) {
                    this.CountriesRegionsDdlField = value;
                    this.RaisePropertyChanged("CountriesRegionsDdl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryRegionCode {
            get {
                return this.CountryRegionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryRegionCodeField, value) != true)) {
                    this.CountryRegionCodeField = value;
                    this.RaisePropertyChanged("CountryRegionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryRegionNames {
            get {
                return this.CountryRegionNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryRegionNamesField, value) != true)) {
                    this.CountryRegionNamesField = value;
                    this.RaisePropertyChanged("CountryRegionNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnlyStateProvinceFlag {
            get {
                return this.IsOnlyStateProvinceFlagField;
            }
            set {
                if ((this.IsOnlyStateProvinceFlagField.Equals(value) != true)) {
                    this.IsOnlyStateProvinceFlagField = value;
                    this.RaisePropertyChanged("IsOnlyStateProvinceFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Web.Mvc.SelectListItem[] SalesTerritorriesDdl {
            get {
                return this.SalesTerritorriesDdlField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesTerritorriesDdlField, value) != true)) {
                    this.SalesTerritorriesDdlField = value;
                    this.RaisePropertyChanged("SalesTerritorriesDdl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateProvinceCode {
            get {
                return this.StateProvinceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StateProvinceCodeField, value) != true)) {
                    this.StateProvinceCodeField = value;
                    this.RaisePropertyChanged("StateProvinceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateProvinceID {
            get {
                return this.StateProvinceIDField;
            }
            set {
                if ((this.StateProvinceIDField.Equals(value) != true)) {
                    this.StateProvinceIDField = value;
                    this.RaisePropertyChanged("StateProvinceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TerritorryNames {
            get {
                return this.TerritorryNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.TerritorryNamesField, value) != true)) {
                    this.TerritorryNamesField = value;
                    this.RaisePropertyChanged("TerritorryNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TerritoryID {
            get {
                return this.TerritoryIDField;
            }
            set {
                if ((this.TerritoryIDField.Equals(value) != true)) {
                    this.TerritoryIDField = value;
                    this.RaisePropertyChanged("TerritoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid {
            get {
                return this.rowguidField;
            }
            set {
                if ((this.rowguidField.Equals(value) != true)) {
                    this.rowguidField = value;
                    this.RaisePropertyChanged("rowguid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CountryRegion", Namespace="http://schemas.datacontract.org/2004/07/AdventureWorks.Model")]
    [System.SerializableAttribute()]
    public partial class CountryRegion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryRegionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PersoneManagement.Web.StateProvinceService.SalesTerritory[] SalesTerritoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PersoneManagement.Web.StateProvinceService.StateProvince[] StateProvincesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryRegionCode {
            get {
                return this.CountryRegionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryRegionCodeField, value) != true)) {
                    this.CountryRegionCodeField = value;
                    this.RaisePropertyChanged("CountryRegionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersoneManagement.Web.StateProvinceService.SalesTerritory[] SalesTerritories {
            get {
                return this.SalesTerritoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesTerritoriesField, value) != true)) {
                    this.SalesTerritoriesField = value;
                    this.RaisePropertyChanged("SalesTerritories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersoneManagement.Web.StateProvinceService.StateProvince[] StateProvinces {
            get {
                return this.StateProvincesField;
            }
            set {
                if ((object.ReferenceEquals(this.StateProvincesField, value) != true)) {
                    this.StateProvincesField = value;
                    this.RaisePropertyChanged("StateProvinces");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesTerritory", Namespace="http://schemas.datacontract.org/2004/07/AdventureWorks.Model")]
    [System.SerializableAttribute()]
    public partial class SalesTerritory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CostLastYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CostYTDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PersoneManagement.Web.StateProvinceService.CountryRegion CountryRegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryRegionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalesLastYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalesYTDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PersoneManagement.Web.StateProvinceService.StateProvince[] StateProvincesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TerritoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid rowguidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CostLastYear {
            get {
                return this.CostLastYearField;
            }
            set {
                if ((this.CostLastYearField.Equals(value) != true)) {
                    this.CostLastYearField = value;
                    this.RaisePropertyChanged("CostLastYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CostYTD {
            get {
                return this.CostYTDField;
            }
            set {
                if ((this.CostYTDField.Equals(value) != true)) {
                    this.CostYTDField = value;
                    this.RaisePropertyChanged("CostYTD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersoneManagement.Web.StateProvinceService.CountryRegion CountryRegion {
            get {
                return this.CountryRegionField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryRegionField, value) != true)) {
                    this.CountryRegionField = value;
                    this.RaisePropertyChanged("CountryRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryRegionCode {
            get {
                return this.CountryRegionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryRegionCodeField, value) != true)) {
                    this.CountryRegionCodeField = value;
                    this.RaisePropertyChanged("CountryRegionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SalesLastYear {
            get {
                return this.SalesLastYearField;
            }
            set {
                if ((this.SalesLastYearField.Equals(value) != true)) {
                    this.SalesLastYearField = value;
                    this.RaisePropertyChanged("SalesLastYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SalesYTD {
            get {
                return this.SalesYTDField;
            }
            set {
                if ((this.SalesYTDField.Equals(value) != true)) {
                    this.SalesYTDField = value;
                    this.RaisePropertyChanged("SalesYTD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersoneManagement.Web.StateProvinceService.StateProvince[] StateProvinces {
            get {
                return this.StateProvincesField;
            }
            set {
                if ((object.ReferenceEquals(this.StateProvincesField, value) != true)) {
                    this.StateProvincesField = value;
                    this.RaisePropertyChanged("StateProvinces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TerritoryID {
            get {
                return this.TerritoryIDField;
            }
            set {
                if ((this.TerritoryIDField.Equals(value) != true)) {
                    this.TerritoryIDField = value;
                    this.RaisePropertyChanged("TerritoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid {
            get {
                return this.rowguidField;
            }
            set {
                if ((this.rowguidField.Equals(value) != true)) {
                    this.rowguidField = value;
                    this.RaisePropertyChanged("rowguid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StateProvince", Namespace="http://schemas.datacontract.org/2004/07/AdventureWorks.Model")]
    [System.SerializableAttribute()]
    public partial class StateProvince : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PersoneManagement.Web.StateProvinceService.Address[] AddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PersoneManagement.Web.StateProvinceService.CountryRegion CountryRegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryRegionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnlyStateProvinceFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PersoneManagement.Web.StateProvinceService.SalesTerritory SalesTerritoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateProvinceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateProvinceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TerritoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid rowguidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersoneManagement.Web.StateProvinceService.Address[] Addresses {
            get {
                return this.AddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressesField, value) != true)) {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersoneManagement.Web.StateProvinceService.CountryRegion CountryRegion {
            get {
                return this.CountryRegionField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryRegionField, value) != true)) {
                    this.CountryRegionField = value;
                    this.RaisePropertyChanged("CountryRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryRegionCode {
            get {
                return this.CountryRegionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryRegionCodeField, value) != true)) {
                    this.CountryRegionCodeField = value;
                    this.RaisePropertyChanged("CountryRegionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnlyStateProvinceFlag {
            get {
                return this.IsOnlyStateProvinceFlagField;
            }
            set {
                if ((this.IsOnlyStateProvinceFlagField.Equals(value) != true)) {
                    this.IsOnlyStateProvinceFlagField = value;
                    this.RaisePropertyChanged("IsOnlyStateProvinceFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersoneManagement.Web.StateProvinceService.SalesTerritory SalesTerritory {
            get {
                return this.SalesTerritoryField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesTerritoryField, value) != true)) {
                    this.SalesTerritoryField = value;
                    this.RaisePropertyChanged("SalesTerritory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateProvinceCode {
            get {
                return this.StateProvinceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StateProvinceCodeField, value) != true)) {
                    this.StateProvinceCodeField = value;
                    this.RaisePropertyChanged("StateProvinceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateProvinceID {
            get {
                return this.StateProvinceIDField;
            }
            set {
                if ((this.StateProvinceIDField.Equals(value) != true)) {
                    this.StateProvinceIDField = value;
                    this.RaisePropertyChanged("StateProvinceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TerritoryID {
            get {
                return this.TerritoryIDField;
            }
            set {
                if ((this.TerritoryIDField.Equals(value) != true)) {
                    this.TerritoryIDField = value;
                    this.RaisePropertyChanged("TerritoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid {
            get {
                return this.rowguidField;
            }
            set {
                if ((this.rowguidField.Equals(value) != true)) {
                    this.rowguidField = value;
                    this.RaisePropertyChanged("rowguid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/AdventureWorks.Model")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PersoneManagement.Web.StateProvinceService.BusinessEntityAddress[] BusinessEntityAddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PersoneManagement.Web.StateProvinceService.StateProvince StateProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateProvinceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid rowguidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressID {
            get {
                return this.AddressIDField;
            }
            set {
                if ((this.AddressIDField.Equals(value) != true)) {
                    this.AddressIDField = value;
                    this.RaisePropertyChanged("AddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersoneManagement.Web.StateProvinceService.BusinessEntityAddress[] BusinessEntityAddresses {
            get {
                return this.BusinessEntityAddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessEntityAddressesField, value) != true)) {
                    this.BusinessEntityAddressesField = value;
                    this.RaisePropertyChanged("BusinessEntityAddresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersoneManagement.Web.StateProvinceService.StateProvince StateProvince {
            get {
                return this.StateProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.StateProvinceField, value) != true)) {
                    this.StateProvinceField = value;
                    this.RaisePropertyChanged("StateProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateProvinceID {
            get {
                return this.StateProvinceIDField;
            }
            set {
                if ((this.StateProvinceIDField.Equals(value) != true)) {
                    this.StateProvinceIDField = value;
                    this.RaisePropertyChanged("StateProvinceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid {
            get {
                return this.rowguidField;
            }
            set {
                if ((this.rowguidField.Equals(value) != true)) {
                    this.rowguidField = value;
                    this.RaisePropertyChanged("rowguid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessEntityAddress", Namespace="http://schemas.datacontract.org/2004/07/AdventureWorks.Model")]
    [System.SerializableAttribute()]
    public partial class BusinessEntityAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PersoneManagement.Web.StateProvinceService.Address AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PersoneManagement.Web.StateProvinceService.AddressType AddressTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddressTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PersoneManagement.Web.StateProvinceService.BusinessEntity BusinessEntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BusinessEntityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid rowguidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersoneManagement.Web.StateProvinceService.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressID {
            get {
                return this.AddressIDField;
            }
            set {
                if ((this.AddressIDField.Equals(value) != true)) {
                    this.AddressIDField = value;
                    this.RaisePropertyChanged("AddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersoneManagement.Web.StateProvinceService.AddressType AddressType {
            get {
                return this.AddressTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressTypeField, value) != true)) {
                    this.AddressTypeField = value;
                    this.RaisePropertyChanged("AddressType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressTypeID {
            get {
                return this.AddressTypeIDField;
            }
            set {
                if ((this.AddressTypeIDField.Equals(value) != true)) {
                    this.AddressTypeIDField = value;
                    this.RaisePropertyChanged("AddressTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersoneManagement.Web.StateProvinceService.BusinessEntity BusinessEntity {
            get {
                return this.BusinessEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessEntityField, value) != true)) {
                    this.BusinessEntityField = value;
                    this.RaisePropertyChanged("BusinessEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BusinessEntityID {
            get {
                return this.BusinessEntityIDField;
            }
            set {
                if ((this.BusinessEntityIDField.Equals(value) != true)) {
                    this.BusinessEntityIDField = value;
                    this.RaisePropertyChanged("BusinessEntityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid {
            get {
                return this.rowguidField;
            }
            set {
                if ((this.rowguidField.Equals(value) != true)) {
                    this.rowguidField = value;
                    this.RaisePropertyChanged("rowguid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressType", Namespace="http://schemas.datacontract.org/2004/07/AdventureWorks.Model")]
    [System.SerializableAttribute()]
    public partial class AddressType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddressTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PersoneManagement.Web.StateProvinceService.BusinessEntityAddress[] BusinessEntityAddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid rowguidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressTypeID {
            get {
                return this.AddressTypeIDField;
            }
            set {
                if ((this.AddressTypeIDField.Equals(value) != true)) {
                    this.AddressTypeIDField = value;
                    this.RaisePropertyChanged("AddressTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersoneManagement.Web.StateProvinceService.BusinessEntityAddress[] BusinessEntityAddresses {
            get {
                return this.BusinessEntityAddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessEntityAddressesField, value) != true)) {
                    this.BusinessEntityAddressesField = value;
                    this.RaisePropertyChanged("BusinessEntityAddresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid {
            get {
                return this.rowguidField;
            }
            set {
                if ((this.rowguidField.Equals(value) != true)) {
                    this.rowguidField = value;
                    this.RaisePropertyChanged("rowguid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessEntity", Namespace="http://schemas.datacontract.org/2004/07/AdventureWorks.Model")]
    [System.SerializableAttribute()]
    public partial class BusinessEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PersoneManagement.Web.StateProvinceService.BusinessEntityAddress[] BusinessEntityAddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BusinessEntityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PersoneManagement.Web.StateProvinceService.Person PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid rowguidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersoneManagement.Web.StateProvinceService.BusinessEntityAddress[] BusinessEntityAddresses {
            get {
                return this.BusinessEntityAddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessEntityAddressesField, value) != true)) {
                    this.BusinessEntityAddressesField = value;
                    this.RaisePropertyChanged("BusinessEntityAddresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BusinessEntityID {
            get {
                return this.BusinessEntityIDField;
            }
            set {
                if ((this.BusinessEntityIDField.Equals(value) != true)) {
                    this.BusinessEntityIDField = value;
                    this.RaisePropertyChanged("BusinessEntityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersoneManagement.Web.StateProvinceService.Person Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid {
            get {
                return this.rowguidField;
            }
            set {
                if ((this.rowguidField.Equals(value) != true)) {
                    this.rowguidField = value;
                    this.RaisePropertyChanged("rowguid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/AdventureWorks.Model")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.Linq.XElement AdditionalContactInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PersoneManagement.Web.StateProvinceService.BusinessEntity BusinessEntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BusinessEntityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.Linq.XElement DemographicsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmailPromotionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NameStyleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuffixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid rowguidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.Linq.XElement AdditionalContactInfo {
            get {
                return this.AdditionalContactInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalContactInfoField, value) != true)) {
                    this.AdditionalContactInfoField = value;
                    this.RaisePropertyChanged("AdditionalContactInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersoneManagement.Web.StateProvinceService.BusinessEntity BusinessEntity {
            get {
                return this.BusinessEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessEntityField, value) != true)) {
                    this.BusinessEntityField = value;
                    this.RaisePropertyChanged("BusinessEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BusinessEntityID {
            get {
                return this.BusinessEntityIDField;
            }
            set {
                if ((this.BusinessEntityIDField.Equals(value) != true)) {
                    this.BusinessEntityIDField = value;
                    this.RaisePropertyChanged("BusinessEntityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.Linq.XElement Demographics {
            get {
                return this.DemographicsField;
            }
            set {
                if ((object.ReferenceEquals(this.DemographicsField, value) != true)) {
                    this.DemographicsField = value;
                    this.RaisePropertyChanged("Demographics");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmailPromotion {
            get {
                return this.EmailPromotionField;
            }
            set {
                if ((this.EmailPromotionField.Equals(value) != true)) {
                    this.EmailPromotionField = value;
                    this.RaisePropertyChanged("EmailPromotion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NameStyle {
            get {
                return this.NameStyleField;
            }
            set {
                if ((this.NameStyleField.Equals(value) != true)) {
                    this.NameStyleField = value;
                    this.RaisePropertyChanged("NameStyle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonType {
            get {
                return this.PersonTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonTypeField, value) != true)) {
                    this.PersonTypeField = value;
                    this.RaisePropertyChanged("PersonType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suffix {
            get {
                return this.SuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.SuffixField, value) != true)) {
                    this.SuffixField = value;
                    this.RaisePropertyChanged("Suffix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid {
            get {
                return this.rowguidField;
            }
            set {
                if ((this.rowguidField.Equals(value) != true)) {
                    this.rowguidField = value;
                    this.RaisePropertyChanged("rowguid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesTerritorryDTO", Namespace="http://schemas.datacontract.org/2004/07/PersoneManagement.Web.Models.DTO")]
    [System.SerializableAttribute()]
    public partial class SalesTerritorryDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryRegionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TerritoryIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryRegionCode {
            get {
                return this.CountryRegionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryRegionCodeField, value) != true)) {
                    this.CountryRegionCodeField = value;
                    this.RaisePropertyChanged("CountryRegionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TerritoryID {
            get {
                return this.TerritoryIDField;
            }
            set {
                if ((this.TerritoryIDField.Equals(value) != true)) {
                    this.TerritoryIDField = value;
                    this.RaisePropertyChanged("TerritoryID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CountryRegionDTO", Namespace="http://schemas.datacontract.org/2004/07/AdventureWorks.Model")]
    [System.SerializableAttribute()]
    public partial class CountryRegionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryRegionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryRegionCode {
            get {
                return this.CountryRegionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryRegionCodeField, value) != true)) {
                    this.CountryRegionCodeField = value;
                    this.RaisePropertyChanged("CountryRegionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StateProvinceService.IStateProvinceService")]
    public interface IStateProvinceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/GetAll", ReplyAction="http://tempuri.org/IStateProvinceService/GetAllResponse")]
        PersoneManagement.Web.StateProvinceService.StateProvinceDTO[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/GetAll", ReplyAction="http://tempuri.org/IStateProvinceService/GetAllResponse")]
        System.Threading.Tasks.Task<PersoneManagement.Web.StateProvinceService.StateProvinceDTO[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/GetStateProvinceById", ReplyAction="http://tempuri.org/IStateProvinceService/GetStateProvinceByIdResponse")]
        PersoneManagement.Web.StateProvinceService.StateProvinceDTO GetStateProvinceById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/GetStateProvinceById", ReplyAction="http://tempuri.org/IStateProvinceService/GetStateProvinceByIdResponse")]
        System.Threading.Tasks.Task<PersoneManagement.Web.StateProvinceService.StateProvinceDTO> GetStateProvinceByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/GetTerritoriesByRegionCode", ReplyAction="http://tempuri.org/IStateProvinceService/GetTerritoriesByRegionCodeResponse")]
        PersoneManagement.Web.StateProvinceService.SalesTerritorryDTO[] GetTerritoriesByRegionCode(string regionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/GetTerritoriesByRegionCode", ReplyAction="http://tempuri.org/IStateProvinceService/GetTerritoriesByRegionCodeResponse")]
        System.Threading.Tasks.Task<PersoneManagement.Web.StateProvinceService.SalesTerritorryDTO[]> GetTerritoriesByRegionCodeAsync(string regionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/GetTerritoriesIdByName", ReplyAction="http://tempuri.org/IStateProvinceService/GetTerritoriesIdByNameResponse")]
        int GetTerritoriesIdByName(string territoriesName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/GetTerritoriesIdByName", ReplyAction="http://tempuri.org/IStateProvinceService/GetTerritoriesIdByNameResponse")]
        System.Threading.Tasks.Task<int> GetTerritoriesIdByNameAsync(string territoriesName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/GetAllTerritories", ReplyAction="http://tempuri.org/IStateProvinceService/GetAllTerritoriesResponse")]
        PersoneManagement.Web.StateProvinceService.SalesTerritorryDTO[] GetAllTerritories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/GetAllTerritories", ReplyAction="http://tempuri.org/IStateProvinceService/GetAllTerritoriesResponse")]
        System.Threading.Tasks.Task<PersoneManagement.Web.StateProvinceService.SalesTerritorryDTO[]> GetAllTerritoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/GetCountryRegions", ReplyAction="http://tempuri.org/IStateProvinceService/GetCountryRegionsResponse")]
        PersoneManagement.Web.StateProvinceService.CountryRegionDTO[] GetCountryRegions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/GetCountryRegions", ReplyAction="http://tempuri.org/IStateProvinceService/GetCountryRegionsResponse")]
        System.Threading.Tasks.Task<PersoneManagement.Web.StateProvinceService.CountryRegionDTO[]> GetCountryRegionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/GetCountryRegionIdByName", ReplyAction="http://tempuri.org/IStateProvinceService/GetCountryRegionIdByNameResponse")]
        string GetCountryRegionIdByName(string regionName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/GetCountryRegionIdByName", ReplyAction="http://tempuri.org/IStateProvinceService/GetCountryRegionIdByNameResponse")]
        System.Threading.Tasks.Task<string> GetCountryRegionIdByNameAsync(string regionName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/ImportFromExcel", ReplyAction="http://tempuri.org/IStateProvinceService/ImportFromExcelResponse")]
        void ImportFromExcel(PersoneManagement.Web.StateProvinceService.StateProvinceDTO stateProvinceDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/ImportFromExcel", ReplyAction="http://tempuri.org/IStateProvinceService/ImportFromExcelResponse")]
        System.Threading.Tasks.Task ImportFromExcelAsync(PersoneManagement.Web.StateProvinceService.StateProvinceDTO stateProvinceDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/InsertStateProvince", ReplyAction="http://tempuri.org/IStateProvinceService/InsertStateProvinceResponse")]
        void InsertStateProvince(PersoneManagement.Web.StateProvinceService.StateProvinceDTO stateProvinceDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/InsertStateProvince", ReplyAction="http://tempuri.org/IStateProvinceService/InsertStateProvinceResponse")]
        System.Threading.Tasks.Task InsertStateProvinceAsync(PersoneManagement.Web.StateProvinceService.StateProvinceDTO stateProvinceDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/UpdateStateProvince", ReplyAction="http://tempuri.org/IStateProvinceService/UpdateStateProvinceResponse")]
        void UpdateStateProvince(PersoneManagement.Web.StateProvinceService.StateProvinceDTO stateProvinceDTO, System.Guid oldGUid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/UpdateStateProvince", ReplyAction="http://tempuri.org/IStateProvinceService/UpdateStateProvinceResponse")]
        System.Threading.Tasks.Task UpdateStateProvinceAsync(PersoneManagement.Web.StateProvinceService.StateProvinceDTO stateProvinceDTO, System.Guid oldGUid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/DeleteStateProvince", ReplyAction="http://tempuri.org/IStateProvinceService/DeleteStateProvinceResponse")]
        void DeleteStateProvince(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateProvinceService/DeleteStateProvince", ReplyAction="http://tempuri.org/IStateProvinceService/DeleteStateProvinceResponse")]
        System.Threading.Tasks.Task DeleteStateProvinceAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStateProvinceServiceChannel : PersoneManagement.Web.StateProvinceService.IStateProvinceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StateProvinceServiceClient : System.ServiceModel.ClientBase<PersoneManagement.Web.StateProvinceService.IStateProvinceService>, PersoneManagement.Web.StateProvinceService.IStateProvinceService {
        
        public StateProvinceServiceClient() {
        }
        
        public StateProvinceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StateProvinceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StateProvinceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StateProvinceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PersoneManagement.Web.StateProvinceService.StateProvinceDTO[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<PersoneManagement.Web.StateProvinceService.StateProvinceDTO[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public PersoneManagement.Web.StateProvinceService.StateProvinceDTO GetStateProvinceById(int id) {
            return base.Channel.GetStateProvinceById(id);
        }
        
        public System.Threading.Tasks.Task<PersoneManagement.Web.StateProvinceService.StateProvinceDTO> GetStateProvinceByIdAsync(int id) {
            return base.Channel.GetStateProvinceByIdAsync(id);
        }
        
        public PersoneManagement.Web.StateProvinceService.SalesTerritorryDTO[] GetTerritoriesByRegionCode(string regionCode) {
            return base.Channel.GetTerritoriesByRegionCode(regionCode);
        }
        
        public System.Threading.Tasks.Task<PersoneManagement.Web.StateProvinceService.SalesTerritorryDTO[]> GetTerritoriesByRegionCodeAsync(string regionCode) {
            return base.Channel.GetTerritoriesByRegionCodeAsync(regionCode);
        }
        
        public int GetTerritoriesIdByName(string territoriesName) {
            return base.Channel.GetTerritoriesIdByName(territoriesName);
        }
        
        public System.Threading.Tasks.Task<int> GetTerritoriesIdByNameAsync(string territoriesName) {
            return base.Channel.GetTerritoriesIdByNameAsync(territoriesName);
        }
        
        public PersoneManagement.Web.StateProvinceService.SalesTerritorryDTO[] GetAllTerritories() {
            return base.Channel.GetAllTerritories();
        }
        
        public System.Threading.Tasks.Task<PersoneManagement.Web.StateProvinceService.SalesTerritorryDTO[]> GetAllTerritoriesAsync() {
            return base.Channel.GetAllTerritoriesAsync();
        }
        
        public PersoneManagement.Web.StateProvinceService.CountryRegionDTO[] GetCountryRegions() {
            return base.Channel.GetCountryRegions();
        }
        
        public System.Threading.Tasks.Task<PersoneManagement.Web.StateProvinceService.CountryRegionDTO[]> GetCountryRegionsAsync() {
            return base.Channel.GetCountryRegionsAsync();
        }
        
        public string GetCountryRegionIdByName(string regionName) {
            return base.Channel.GetCountryRegionIdByName(regionName);
        }
        
        public System.Threading.Tasks.Task<string> GetCountryRegionIdByNameAsync(string regionName) {
            return base.Channel.GetCountryRegionIdByNameAsync(regionName);
        }
        
        public void ImportFromExcel(PersoneManagement.Web.StateProvinceService.StateProvinceDTO stateProvinceDTO) {
            base.Channel.ImportFromExcel(stateProvinceDTO);
        }
        
        public System.Threading.Tasks.Task ImportFromExcelAsync(PersoneManagement.Web.StateProvinceService.StateProvinceDTO stateProvinceDTO) {
            return base.Channel.ImportFromExcelAsync(stateProvinceDTO);
        }
        
        public void InsertStateProvince(PersoneManagement.Web.StateProvinceService.StateProvinceDTO stateProvinceDTO) {
            base.Channel.InsertStateProvince(stateProvinceDTO);
        }
        
        public System.Threading.Tasks.Task InsertStateProvinceAsync(PersoneManagement.Web.StateProvinceService.StateProvinceDTO stateProvinceDTO) {
            return base.Channel.InsertStateProvinceAsync(stateProvinceDTO);
        }
        
        public void UpdateStateProvince(PersoneManagement.Web.StateProvinceService.StateProvinceDTO stateProvinceDTO, System.Guid oldGUid) {
            base.Channel.UpdateStateProvince(stateProvinceDTO, oldGUid);
        }
        
        public System.Threading.Tasks.Task UpdateStateProvinceAsync(PersoneManagement.Web.StateProvinceService.StateProvinceDTO stateProvinceDTO, System.Guid oldGUid) {
            return base.Channel.UpdateStateProvinceAsync(stateProvinceDTO, oldGUid);
        }
        
        public void DeleteStateProvince(int id) {
            base.Channel.DeleteStateProvince(id);
        }
        
        public System.Threading.Tasks.Task DeleteStateProvinceAsync(int id) {
            return base.Channel.DeleteStateProvinceAsync(id);
        }
    }
}
